version: "3.7"

services:
  #### notifier
  notifier:
    image: vizitiuroman/notifier-service:1.0.0
    container_name: notifier
    ports:
      - "8070:8070"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8070/ping" ]
      interval: 1m
      timeout: 3s
      start_period: 10s
      retries: 3
    environment:
      - PORT=8070
      - FIREBASEKEY=AAAARqguap4:APA91bFGJmFQNeAGwuN453OTKwNIT-v6c_54PLgNDS2WORi8qVG0LtctX4OClcLRkjzrJMAfboDE5sRKKAD0mD-VN1JJXnvtb_2T9NmWtDCMiFNnFdBNh2PypZ_Kt6OjG5kYKttRnSe8
